apiVersion: v1
kind: Pod
metadata:
  name: counter
  labels:
    app: counter
    tier: backend
spec:
  containers:
    - name: counter
      image: ghcr.io/subicura/counter:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: REDIS_HOST
          value: "localhost"
    - name: db
      image: redis
  restartPolicy: Always
