apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 2
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
        tier: db
    spec:
      containers:
        - name: mysql
          image: mariadb:10.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_DATABASE
              value: k8s
            - name: MYSQL_ROOT_PASSWORD
              value: k8s
          ports:
            - containerPort: 3306
              protocol: TCP
      restartPolicy: Always
  selector:
    matchLabels:
      app: mysql
      tier: db

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
    tier: db
  ports:
    - port: 3306
      protocol: TCP