apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 2
  template:
    metadata:
      name: wordpress
      labels:
        app: wordpress
        tier: app
    spec:
      containers:
        - name: wordpress
          image: wordpress:5.9.1-php8.1-apache
          imagePullPolicy: IfNotPresent
          env:
            - name: WORDPRESS_DB_HOST
              value: "mysql"
            - name: WORDPRESS_DB_NAME
              value: "k8s"
            - name: WORDPRESS_DB_USER
              value: "root"
            - name: WORDPRESS_DB_PASSWORD
              value: k8s
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
  selector:
    matchLabels:
      app: wordpress
      tier: app

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
    tier: app
  ports:
    - port: 80
      protocol: TCP
      nodePort: 30000
  type: NodePort