apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deploy
  labels:
    app: echo
spec:
  replicas: 3
  template:
    metadata:
      name: echo
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: ghcr.io/subicura/echo:v2
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: echo
