apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: counter
        tier: db
    spec:
      containers:
        - name: redis
          image: redis
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always
  selector:
    matchLabels:
      app: counter
      tier: db

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: counter
    tier: db
  ports:
    - port: 6379
      protocol: TCP